
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOB8FKHg","is_bot":false,"login":"shuyiwan","name":"Shuyi Wan"},"headRefName":"Shuyi-HelpRequest-FixTypo","number":116,"title":"fixed typo in HelpRequestForm about solved","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-4/pull/116"},{"author":{"id":"MDQ6VXNlcjgwMDY1NjAx","is_bot":false,"login":"sumitgupta314","name":"Sumit Gupta"},"headRefName":"sg-fix-table-bool","number":115,"title":"sg - #28 - fixed boolean (done) to be displayed","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-4/pull/115"}]
